# Generated by Django 4.2.30 on 2026-05-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productgalleryimage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Product gallery image', 'verbose_name_plural': 'Product gallery images'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productgalleryimage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
